### ISSUE TITLE
html5 problems

### ISSUE THREAD

**Issue by alex-codes-stuff** [ShadowMario/FNF-PsychEngine#11709]
### Describe your problem here.

whenever i compile to html5, the webpage loads and the haxeflixel loading thingy also loads, but then its just a black screen. how do i fix this?
and also, how can i make it so other people can play the html5 build?

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

yes, its a mod

**Comment by TheKitBoi** [comment]
if ur using chrome check developer tools on the 3 dots

**Comment by alex-codes-stuff** [comment]
i saw this error
haxe_ValueException
message
: 
"[lime.utils.Assets] ERROR: There is no SOUND asset with an ID of \"assets/music/title.mp3\""
value
: 
"[lime.utils.Assets] ERROR: There is no SOUND asset with an ID of \"assets/music/title.mp3\""
__nativeException
: 
haxe_ValueException {message: '[lime.utils.Assets] ERROR: There is no SOUND asset with an ID of "assets/music/title.mp3"', __previousException: undefined, __nativeException: haxe_ValueException, __skipStack: 2, value: '[lime.utils.Assets] ERROR: There is no SOUND asset with an ID of "assets/music/title.mp3"', …}
__previousException
: 
undefined
__skipStack
: 
2
stack
: 
"Error: [lime.utils.Assets] ERROR: There is no SOUND asset with an ID of \"assets/music/title.mp3\"\n    at new haxe_ValueException (http://127.0.0.1:3000/Meme%20Mania.js:119592:17)\n    at haxe_Exception.thrown (http://127.0.0.1:3000/Meme%20Mania.js:118632:11)\n    at lime_utils_Log.error (http://127.0.0.1:3000/Meme%20Mania.js:141002:25)\n    at lime_utils_Assets.getAsset (http://127.0.0.1:3000/Meme%20Mania.js:140031:19)\n    at lime_utils_Assets.getAudioBuffer (http://127.0.0.1:3000/Meme%20Mania.js:140042:27)\n    at openfl_utils_Assets.getSound (http://127.0.0.1:3000/Meme%20Mania.js:186908:33)\n    at Paths.returnSound (http://127.0.0.1:3000/Meme%20Mania.js:35923:35)\n    at TitleState.startIntro (http://127.0.0.1:3000/Meme%20Mania.js:43273:22)\n    at TitleState.create (http://127.0.0.1:3000/Meme%20Mania.js:43255:9)\n    at flixel_FlxGame.switchState (http://127.0.0.1:3000/Meme%20Mania.js:58029:15)"
[[Prototype]]
: 
Error

**Comment by Yuta12342** [comment]
Doesn't FNF usually use ogg files, and not mp3s? I dunno if that has anything to do with it.

**Comment by skgdraws** [comment]
ok, for html5 builds, FNF uses .mp3 files instead of .ogg files
