### ISSUE TITLE
0.5 builds won't build in github actions and a "TypeError: this.text.indexOf is not a function" in chart editor

### ISSUE THREAD

**Issue by Spongeyboi** [ShadowMario/FNF-PsychEngine#5955]
### Describe your bug here.

The game randomly crashes when on the chart editor, or if you place down numbered notes (hurt note, gf sing note, etc). I'm on Psych Engine 0.4.2 because the 0.5 builds refuses to build (seen below).
![image](https://user-images.githubusercontent.com/71215126/155991896-086b26aa-cb60-4a82-af03-fc74cb167e96.png)

The main problem I have is this crash error seen below
![image](https://user-images.githubusercontent.com/71215126/155991053-3a4dacca-4477-4fb6-a841-8ac2f9849337.png)

### Command Prompt/Terminal logs (if existing)

```bash
Uncaught TypeError: this.text.indexOf is not a function
    at openfl_text__$internal_TextEngine.getLayoutGroups (PsychEngine.js:168830:30)
    at openfl_text__$internal_TextEngine.update (PsychEngine.js:169413:9)
    at openfl_text_TextField.__updateLayout (PsychEngine.js:130201:22)
    at openfl_text_TextField.get_width (PsychEngine.js:130744:8)
    at flixel_addons_ui_FlxUIInputText.regenGraphic (PsychEngine.js:27368:33)
    at flixel_addons_ui_FlxUIInputText.draw (PsychEngine.js:27418:8)
    at flixel_addons_ui_FlxUIInputText.draw (PsychEngine.js:52703:38)
    at flixel_group_FlxTypedGroup.draw (PsychEngine.js:3925:11)
    at flixel_addons_ui_FlxUI.draw (PsychEngine.js:3114:14)
    at flixel_group_FlxTypedGroup.draw (PsychEngine.js:3925:11)
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

HTML5

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by Spongeyboi** [comment]
Ok, I decided to use the git version which fixed some of the problems (I edited out some other errors, sys in js bs) and now part 1 is resolved. Now that openfl error that happens during charting.
