### ISSUE TITLE
HTML5 build gets stuck on a black screen after dismissing the warning

### ISSUE THREAD

**Issue by CoolGuyisHere** [ShadowMario/FNF-PsychEngine#7950]
### Describe your bug here.

Basically, after I press either enter or escape to dismiss the warning when you first start up the game, it just stays on a black screen and doesn't allow you to play. Refreshing doesn't work either... I forgot to mention my version, it's 0.5.2h

![bug](https://user-images.githubusercontent.com/96320621/161445155-58692261-7a52-4474-976c-7af8597379ff.PNG)

### Command Prompt/Terminal logs (if existing)

```bash
Dunno if this counts as a "terminal log", but I found this error in the Console of Inspect Element:

Uncaught TypeError: Cannot read properties of undefined (reading 'toUpperCase')
    at TitleState.startIntro (PsychEngine.js:36108:22)
    at flixel_util_FlxTimer.onComplete (PsychEngine.js:36049:12)
    at flixel_util_FlxTimer.onLoopFinished (PsychEngine.js:102807:9)
    at flixel_util_FlxTimerManager.update (PsychEngine.js:102868:56)
    at flixel_FlxGame.update (PsychEngine.js:49887:12)
    at flixel_FlxGame.step (PsychEngine.js:49865:8)
    at flixel_FlxGame.onEnterFrame (PsychEngine.js:49799:11)
    at openfl_display_Stage.__dispatchEvent (PsychEngine.js:6478:15)
    at openfl_display_Stage.__dispatch (PsychEngine.js:7291:73)
    at openfl_display_Stage.__broadcastEvent (PsychEngine.js:137530:18)

startIntro	@	PsychEngine.js:36108
(anonymous)	@	PsychEngine.js:36049
onLoopFinished	@	PsychEngine.js:102807
update	@	PsychEngine.js:102868
update	@	PsychEngine.js:49887
step	@	PsychEngine.js:49865
onEnterFrame	@	PsychEngine.js:49799
__dispatchEvent	@	PsychEngine.js:6478
__dispatch	@	PsychEngine.js:7291
__broadcastEvent	@	PsychEngine.js:137530
__onLimeRender	@	PsychEngine.js:138557
dispatch	@	PsychEngine.js:116652
handleApplicationEvent	@	PsychEngine.js:5676
requestAnimationFrame (async)		
handleApplicationEvent	@	PsychEngine.js:5686
requestAnimationFrame (async)		
handleApplicationEvent	@	PsychEngine.js:5686
requestAnimationFrame (async)		
handleApplicationEvent	@	PsychEngine.js:5686
requestAnimationFrame (async)		
handleApplicationEvent	@	PsychEngine.js:5686
requestAnimationFrame (async)		
handleApplicationEvent	@	PsychEngine.js:5686
requestAnimationFrame (async)		
handleApplicationEvent	@	PsychEngine.js:5686
requestAnimationFrame (async)		
handleApplicationEvent	@	PsychEngine.js:5686
requestAnimationFrame (async)		
handleApplicationEvent	@	PsychEngine.js:5686
requestAnimationFrame (async)		
handleApplicationEvent	@	PsychEngine.js:5686
requestAnimationFrame (async)		
handleApplicationEvent	@	PsychEngine.js:5686
requestAnimationFrame (async)		
handleApplicationEvent	@	PsychEngine.js:5686
requestAnimationFrame (async)		
handleApplicationEvent	@	PsychEngine.js:5686
requestAnimationFrame (async)		
handleApplicationEvent	@	PsychEngine.js:5686
requestAnimationFrame (async)		
handleApplicationEvent	@	PsychEngine.js:5686
requestAnimationFrame (async)		
handleApplicationEvent	@	PsychEngine.js:5686
requestAnimationFrame (async)		
handleApplicationEvent	@	PsychEngine.js:5686
requestAnimationFrame (async)		
handleApplicationEvent	@	PsychEngine.js:5686
requestAnimationFrame (async)		
handleApplicationEvent	@	PsychEngine.js:5686
requestAnimationFrame (async)		
handleApplicationEvent	@	PsychEngine.js:5686
requestAnimationFrame (async)		
handleApplicationEvent	@	PsychEngine.js:5686
requestAnimationFrame (async)		
handleApplicationEvent	@	PsychEngine.js:5686
requestAnimationFrame (async)		
handleApplicationEvent	@	PsychEngine.js:5686
requestAnimationFrame (async)		
handleApplicationEvent	@	PsychEngine.js:5686
requestAnimationFrame (async)		
handleApplicationEvent	@	PsychEngine.js:5686
requestAnimationFrame (async)		
handleApplicationEvent	@	PsychEngine.js:5686
requestAnimationFrame (async)		
handleApplicationEvent	@	PsychEngine.js:5686
requestAnimationFrame (async)		
handleApplicationEvent	@	PsychEngine.js:5686
requestAnimationFrame (async)		
handleApplicationEvent	@	PsychEngine.js:5686
requestAnimationFrame (async)		
handleApplicationEvent	@	PsychEngine.js:5686
requestAnimationFrame (async)		
handleApplicationEvent	@	PsychEngine.js:5686
requestAnimationFrame (async)		
handleApplicationEvent	@	PsychEngine.js:5686
requestAnimationFrame (async)		
handleApplicationEvent	@	PsychEngine.js:5686
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

HTML5

### Did you edit anything in this build? If so, mention or summarize your changes.

No, just added all of the base stuff from the original compile

**Comment by PrismLight** [comment]
Did you delete every line for sys.io?
I've had this problem before.

**Comment by CoolGuyisHere** [comment]
> Did you delete every line for sys.io? I've had this problem before.

Yes, I've deleted every line containing sys.io, the only errors I get whilst compiling are the usual 'deprecated' errors which shouldn't affect booting the game at all

**Comment by CoolGuyisHere** [comment]
HELLO Friends, I may have found a fix for this issue However I haven't tested it yet. But I think it should work... I'll close this if it does

Here da link: https://github.com/Starmapo/FNF-PsychEngine-Extra/issues/11#issuecomment-1093299756
